# Домашнее задание

## Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [26]:
N = 10

In [27]:
for i in range(int(N)):
    numpy_array = np.array( [i] ) if i == 0 else np.concatenate((np.array( [i] ), numpy_array))
numpy_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [28]:
matrix = np.diag(numpy_array, k=0)
matrix

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [29]:
sum_=0
i=0
for string in matrix:
    sum_ += int(string[i])
    i += 1

sum_

45

## Задание 3

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [32]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

In [31]:
from numpy import linalg

In [33]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [34]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

## Задание 4

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [35]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [36]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [37]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [54]:
user_cosine = {}
i=0
for user in users_stats:
    user_cosine.setdefault(i, cosine(user, next_user_stats))
    i+=1
user_cosine

{0: 0.19999999999999996,
 1: 0.8451542547285165,
 2: 0.3999999999999999,
 3: 0.7905694150420948,
 4: 0.3999999999999999,
 5: 0.0,
 6: 0.0,
 7: 0.9486832980505138,
 8: 0.0,
 9: 0.0}

In [58]:
max_ = max(user_cosine.values())
for key, value in user_cosine.items():
    if value == max_:
        print(key)

7
